dataset_name: VN3K_EN
text_length: ${tokenizer.model_max_length}
batch_size: 8
sampler: random
test_batch_size: 64
num_instance: 1
num_workers: 4
proportion: null
noisy_rate: 0.0
noisy_file: null
fn_noisy_rate: 0.0
fn_noisy_file: null
