_target_: peft.LoraConfig
r: 32
lora_alpha: 64
target_modules: ["q_proj", "k_proj", "v_proj", "out_proj", "fc1", "fc2"]
lora_dropout: 0.05
bias: "none"
inference_mode: false
task_type: FEATURE_EXTRACTION
use_rslora: true
